-- AULA 05/08 - CONSULTAS COMPLEXAS

-- DISTINCT
SELECT DISTINCT Salario
FROM FUNCIONARIO

-- WHERE
SELECT *
FROM FUNCIONARIO
WHERE Pnome = 'João';

SELECT *
FROM FUNCIONARIO
WHERE Salario = 25000;

-- AND 
SELECT *
FROM FUNCIONARIO
WHERE Sexo = 'M' AND Salario >= 30000;

-- OR 
SELECT *
FROM FUNCIONARIO AS F
WHERE F.Endereco LIKE '%São Paulo%' OR F.Endereco LIKE '%Curitiba%';

-- NOT 
SELECT *
FROM FUNCIONARIO AS F
WHERE NOT F.Endereco LIKE '%São Paulo%';

-- ORDER BY ASC/DESC
SELECT F.Pnome, F.Unome, F.Salario
FROM FUNCIONARIO AS F
ORDER BY F.Salario DESC;

-- IS NULL 
SELECT *
FROM FUNCIONARIO AS F
WHERE F.Cpf_supervisor IS NULL;

--IS NOT NULL 
SELECT F.Pnome, F.Unome, F.Cpf_supervisor
FROM FUNCIONARIO AS F
WHERE F.Cpf_supervisor IS NOT NULL;

-- SELECT TOP
SELECT TOP 3*
FROM FUNCIONARIO
WHERE Cpf_supervisor IS NOT NULL
ORDER BY Salario DESC;

-- MIN() / MAX()

-- MIN() 
SELECT *
FROM FUNCIONARIO
WHERE Salario = (SELECT MIN(Salario) FROM FUNCIONARIO);

-- MAX
SELECT *
FROM FUNCIONARIO
WHERE Salario = (SELECT MAX(Salario) FROM FUNCIONARIO);

-- DECLARE (Conteúdo novo)
DECLARE @Salario_Min DECIMAL(10,2);

SELECT @Salario_Min = MIN(Salario)
FROM FUNCIONARIO;

SELECT *
FROM FUNCIONARIO
WHERE Salario = @Salario_Min;

-- COUNT()
SELECT COUNT(*) AS 'Total de Funcionários'
FROM FUNCIONARIO;

SELECT COUNT(*) 'Total de Dependentes'
FROM DEPENDENTE;

SELECT
	(SELECT COUNT(*) FROM FUNCIONARIO) +
	(SELECT COUNT(*) FROM DEPENDENTE) 
	AS 'Total de Pessoas';

-- AVG() 
SELECT AVG(Salario) AS 'Média Salarial dos Funcionários'
FROM FUNCIONARIO;

SELECT MAX(Salario) AS 'Maior Salário'
FROM FUNCIONARIO;

SELECT
	(SELECT MAX(Salario) FROM FUNCIONARIO) -
	(SELECT AVG(Salario) FROM FUNCIONARIO) 
	AS 'Valor Acima da Média';

-- SUM()
SELECT SUM(Salario) AS 'Custo Mensal'
FROM FUNCIONARIO;

-- LIKE
DECLARE @AnoNascimento Date

SET @AnoNascimento = (SELECT Datanasc FROM FUNCIONARIO WHERE Pnome = 'Joice');

PRINT YEAR(@AnoNascimento);

SELECT *
FROM FUNCIONARIO
WHERE Datanasc LIKE '%72%';

SELECT *
FROM FUNCIONARIO
WHERE YEAR(Datanasc) LIKE '__72';

--IN 
SELECT *
FROM FUNCIONARIO
WHERE Salario IN (25000, 30000);

SELECT F.Cpf
FROM FUNCIONARIO AS F
WHERE F.Pnome = 'Fernando';

SELECT Pnr, Horas
FROM TRABALHA_EM
WHERE Fcpf = (SELECT Cpf FROM FUNCIONARIO WHERE Pnome = 'Fernando');

SELECT *
FROM FUNCIONARIO AS F, TRABALHA_EM AS TE
WHERE F.Cpf = TE.Fcpf -- Junção de tabelas
AND TE.Pnr IN (SELECT Pnr FROM TRABALHA_EM WHERE Fcpf = '33344555587')
AND TE.Horas IN (SELECT Horas FROM TRABALHA_EM WHERE Fcpf = '33344555587')
AND NOT F.Cpf = '33344555587';

SELECT *
FROM FUNCIONARIO AS F
JOIN TRABALHA_EM AS TE ON F.Cpf = TE.Fcpf
WHERE TE.Pnr IN (SELECT Pnr FROM TRABALHA_EM WHERE Fcpf = '33344555587')
AND TE.Horas IN (SELECT Horas FROM TRABALHA_EM WHERE Fcpf = '33344555587')
AND NOT F.Cpf = '33344555587';

-- AS
SELECT Pnome AS 'Nome', Unome AS 'Sobrenome'
FROM FUNCIONARIO;
